import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import toast from 'react-hot-toast'

const ALL_INDIAN_COMPANIES = [
  // IT Services MNCs
  { id: 'tcs', name: 'TCS (Tata Consultancy Services)', logo: '🏢', category: 'IT Services MNC', roles: ['Ninja Engineer', 'Digital Engineer', 'Innovator'], ctc: '₹3.6 - 7.0 LPA' },
  { id: 'infosys', name: 'Infosys', logo: '🔷', category: 'IT Services MNC', roles: ['System Engineer', 'Specialist Programmer', 'Power Programmer'], ctc: '₹3.6 - 9.5 LPA' },
  { id: 'wipro', name: 'Wipro', logo: '🌐', category: 'IT Services MNC', roles: ['Project Engineer', 'Turbo Developer'], ctc: '₹3.5 - 6.5 LPA' },
  { id: 'hcl', name: 'HCLTech', logo: '💻', category: 'IT Services MNC', roles: ['Software Engineer', 'Graduate Trainee'], ctc: '₹3.5 - 5.5 LPA' },
  { id: 'cognizant', name: 'Cognizant (CTS)', logo: '⚡', category: 'IT Services MNC', roles: ['GenC Engineer', 'GenC Elevate', 'GenC Pro'], ctc: '₹4.0 - 6.8 LPA' },
  { id: 'accenture', name: 'Accenture India', logo: '🅰️', category: 'IT Services MNC', roles: ['Associate Software Engineer', 'Advanced Tech Analyst'], ctc: '₹4.5 - 6.5 LPA' },
  { id: 'capgemini', name: 'Capgemini', logo: '♠️', category: 'IT Services MNC', roles: ['Analyst Developer', 'Senior Analyst'], ctc: '₹4.0 - 7.5 LPA' },
  { id: 'techm', name: 'Tech Mahindra', logo: '🔧', category: 'IT Services MNC', roles: ['Associate Software Engineer'], ctc: '₹3.5 - 5.5 LPA' },

  // Product & Tech Giants
  { id: 'zoho', name: 'Zoho Corporation', logo: '🚀', category: 'Product Giant', roles: ['Software Development Engineer', 'UI/UX Developer'], ctc: '₹6.0 - 12.0 LPA' },
  { id: 'amazon', name: 'Amazon India', logo: '📦', category: 'Product Giant', roles: ['SDE-1', 'Cloud Support Engineer', 'Data Analyst'], ctc: '₹14.0 - 28.0 LPA' },
  { id: 'google', name: 'Google India', logo: '🔍', category: 'Product Giant', roles: ['Software Engineer', 'Application Engineer'], ctc: '₹18.0 - 32.0 LPA' },
  { id: 'microsoft', name: 'Microsoft India', logo: '🪟', category: 'Product Giant', roles: ['Software Engineer', 'Data Scientist'], ctc: '₹16.0 - 30.0 LPA' },
  { id: 'flipkart', name: 'Flipkart', logo: '🛍️', category: 'Product Giant', roles: ['SDE-1', 'Product Analyst'], ctc: '₹12.0 - 22.0 LPA' },

  // Core Engineering & PSUs
  { id: 'lt', name: 'Larsen & Toubro (L&T)', logo: '🏗️', category: 'Core Engineering', roles: ['Graduate Engineer Trainee (GET)', 'Design Engineer'], ctc: '₹6.0 - 9.0 LPA' },
  { id: 'bhel', name: 'BHEL (Bharat Heavy Electricals)', logo: '⚡', category: 'PSU / Core', roles: ['Engineer Trainee (ET)', 'Executive Engineer'], ctc: '₹10.0 - 14.0 LPA' },
  { id: 'isro', name: 'ISRO (Indian Space Research Org)', logo: '🚀', category: 'PSU / Space', roles: ['Scientist / Engineer SD', 'Technical Assistant'], ctc: '₹9.0 - 12.0 LPA' },
  { id: 'drdo', name: 'DRDO (Defence Research Org)', logo: '🛡️', category: 'PSU / Defence', roles: ['Scientist B', 'Junior Research Fellow'], ctc: '₹9.0 - 12.0 LPA' },

  // Banking & Financial
  { id: 'ibps', name: 'IBPS (Bank PO & Specialist Officer)', logo: '🏦', category: 'Banking & PSUs', roles: ['IT Officer (Scale-I)', 'Probationary Officer'], ctc: '₹7.0 - 10.0 LPA' },
  { id: 'sbi', name: 'State Bank of India (SBI)', logo: '🏛️', category: 'Banking & PSUs', roles: ['SBI PO', 'SBI IT Specialist'], ctc: '₹8.5 - 12.0 LPA' }
]

const SAMPLE_QUESTIONS = {
  'TCS (Tata Consultancy Services)': [
    { question: 'What is the output of predicting: int x = 5; printf("%d %d", x++, ++x); in C?', options: ['5 7', '6 7', 'Compiler Dependent / Undefined Behavior', '5 6'], answer: 2, explanation: 'Modifying a variable multiple times in printf evaluates in undefined behavior in C standard.' },
    { question: 'Which SQL clause is used to filter aggregated data generated by GROUP BY?', options: ['WHERE', 'HAVING', 'ORDER BY', 'FILTER'], answer: 1, explanation: 'HAVING filters aggregated groups, whereas WHERE filters individual rows.' },
    { question: 'A train 150 meters long passes a telegraph post in 12 seconds. Find the speed of the train in km/hr.', options: ['45 km/hr', '50 km/hr', '36 km/hr', '60 km/hr'], answer: 0, explanation: 'Speed = 150 / 12 = 12.5 m/s. In km/hr = 12.5 * (18/5) = 45 km/hr.' }
  ],
  'Zoho Corporation': [
    { question: 'What is the main advantage of Low-Level Design (LLD) using OOP Principles?', options: ['Faster execution speed', 'Maintainability, Reusability & Extensibility', 'Fewer lines of code', 'No memory allocation needed'], answer: 1, explanation: 'OOP & LLD ensure scalable, reusable, and maintainable software architecture.' },
    { question: 'What is the time complexity of searching an element in a balanced Binary Search Tree (BST)?', options: ['O(N)', 'O(1)', 'O(log N)', 'O(N log N)'], answer: 2, explanation: 'In a balanced BST, height is log N, so search time complexity is O(log N).' }
  ]
}

export default function CompanyMockTests() {
  const [selectedCompany, setSelectedCompany] = useState(ALL_INDIAN_COMPANIES[0])
  const [selectedCategory, setSelectedCategory] = useState('All Categories')
  const [role, setRole] = useState(ALL_INDIAN_COMPANIES[0].roles[0])
  const [difficulty, setDifficulty] = useState('medium')

  const [testActive, setTestActive] = useState(false)
  const [currentQ, setCurrentQ] = useState(0)
  const [userAnswers, setUserAnswers] = useState({})
  const [submitted, setSubmitted] = useState(false)

  const categories = ['All Categories', 'IT Services MNC', 'Product Giant', 'Core Engineering', 'PSU / Core', 'Banking & PSUs']

  const filteredCompanies = ALL_INDIAN_COMPANIES.filter(c => selectedCategory === 'All Categories' || c.category === selectedCategory)

  const activeQuestions = SAMPLE_QUESTIONS[selectedCompany.name] || [
    { question: `What is a primary requirement for ${selectedCompany.name} Technical Selection Round?`, options: ['Strong CS Fundamentals & Data Structures', 'No preparation needed', 'Only general knowledge', 'Typing speed only'], answer: 0, explanation: 'Core CS concepts, Coding logic & Problem Solving are essential for campus placement drives.' },
    { question: 'If A can finish a work in 10 days and B in 15 days, how many days will they take together?', options: ['5 days', '6 days', '7.5 days', '8 days'], answer: 1, explanation: '1/10 + 1/15 = 1/6 work per day. Total time = 6 days.' },
    { question: 'Which Data Structure works on LIFO (Last In First Out) principle?', options: ['Queue', 'Stack', 'Linked List', 'Array'], answer: 1, explanation: 'Stack follows Last In First Out (LIFO).' }
  ]

  const handleStartTest = () => {
    setTestActive(true)
    setCurrentQ(0)
    setUserAnswers({})
    setSubmitted(false)
    toast.success(`🎯 ${selectedCompany.name} Mock Test started!`)
  }

  const handleAnswerSelect = (qIdx, optIdx) => {
    setUserAnswers({ ...userAnswers, [qIdx]: optIdx })
  }

  const score = Object.keys(userAnswers).reduce((acc, qIdx) => {
    return acc + (userAnswers[qIdx] === activeQuestions[qIdx].answer ? 1 : 0)
  }, 0)

  return (
    <div style={{ padding: '1.5rem', maxWidth: '1000px', margin: '0 auto' }}>
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}
        style={{ background: 'linear-gradient(135deg, #1e1b4b, #312e81, #1e293b)', borderRadius: '1.5rem', padding: '2rem', marginBottom: '1.5rem', border: '1px solid rgba(139,92,246,0.3)' }}
      >
        <h1 style={{ fontSize: '2.2rem', fontWeight: '900', color: 'white', marginBottom: '0.5rem' }}>
          📝 All India Company-Wise Placement Mock Tests
        </h1>
        <p style={{ color: '#c4b5fd' }}>
          Mock test patterns for all major Indian MNCs, Product Giants, Core PSUs, ISRO, DRDO & Banking Exams.
        </p>
      </motion.div>

      {!testActive ? (
        <>
          {/* Category Filter */}
          <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.5rem', overflowX: 'auto', paddingBottom: '0.25rem' }}>
            {categories.map(cat => (
              <button
                key={cat} onClick={() => setSelectedCategory(cat)}
                style={{ padding: '0.5rem 1rem', borderRadius: '0.75rem', fontWeight: '600', fontSize: '0.82rem', whiteSpace: 'nowrap', cursor: 'pointer',
                  background: selectedCategory === cat ? 'linear-gradient(135deg, #7c3aed, #2563eb)' : 'rgba(255,255,255,0.05)',
                  color: selectedCategory === cat ? 'white' : '#94a3b8',
                  border: selectedCategory === cat ? 'none' : '1px solid rgba(255,255,255,0.1)'
                }}
              >
                {cat}
              </button>
            ))}
          </div>

          {/* Company Selection Cards */}
          <h2 style={{ color: 'white', fontWeight: '800', fontSize: '1.2rem', marginBottom: '1rem' }}>🏢 Select Target Company ({filteredCompanies.length})</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1.25rem', marginBottom: '2rem' }}>
            {filteredCompanies.map(c => {
              const isSelected = selectedCompany.id === c.id
              return (
                <div
                  key={c.id} onClick={() => { setSelectedCompany(c); setRole(c.roles[0]); }}
                  style={{
                    background: isSelected ? 'linear-gradient(135deg, rgba(124,58,237,0.2), rgba(37,99,235,0.2))' : 'rgba(255,255,255,0.03)',
                    border: `1px solid ${isSelected ? 'rgba(139,92,246,0.5)' : 'rgba(255,255,255,0.08)'}`,
                    borderRadius: '1.25rem', padding: '1.25rem', cursor: 'pointer', transition: 'all 0.2s'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
                    <span style={{ fontSize: '2rem' }}>{c.logo}</span>
                    <div>
                      <h3 style={{ color: 'white', fontWeight: '800', fontSize: '1rem', margin: 0 }}>{c.name}</h3>
                      <span style={{ color: '#94a3b8', fontSize: '0.75rem' }}>{c.category}</span>
                    </div>
                  </div>
                  <div style={{ color: '#4ade80', fontWeight: '800', fontSize: '0.85rem', marginBottom: '0.4rem' }}>Expected CTC: {c.ctc}</div>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.3rem' }}>
                    {c.roles.map(r => <span key={r} style={{ background: 'rgba(255,255,255,0.06)', color: '#cbd5e1', padding: '0.1rem 0.4rem', borderRadius: '0.4rem', fontSize: '0.7rem' }}>{r}</span>)}
                  </div>
                </div>
              )
            })}
          </div>

          {/* Test Setup Box */}
          <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '1.25rem', padding: '1.5rem' }}>
            <h3 style={{ color: 'white', fontWeight: '800', fontSize: '1.1rem', marginBottom: '1rem' }}>⚙️ Test Configuration — {selectedCompany.name}</h3>
            
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginBottom: '1.25rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', color: '#94a3b8', marginBottom: '0.3rem', fontWeight: '600' }}>Select Target Role</label>
                <select value={role} onChange={e => setRole(e.target.value)} style={{ width: '100%', background: 'rgba(30,27,75,0.9)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '0.6rem', padding: '0.6rem 0.9rem', color: 'white', fontSize: '0.9rem', outline: 'none' }}>
                  {selectedCompany.roles.map(r => <option key={r} value={r}>{r}</option>)}
                </select>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', color: '#94a3b8', marginBottom: '0.3rem', fontWeight: '600' }}>Difficulty Level</label>
                <select value={difficulty} onChange={e => setDifficulty(e.target.value)} style={{ width: '100%', background: 'rgba(30,27,75,0.9)', border: '1px solid rgba(139,92,246,0.3)', borderRadius: '0.6rem', padding: '0.6rem 0.9rem', color: 'white', fontSize: '0.9rem', outline: 'none' }}>
                  <option value="easy">🟢 Easy (Basic Aptitude)</option>
                  <option value="medium">🟡 Medium (Actual Placement Standard)</option>
                  <option value="hard">🔴 Hard (Advanced Coding / Gate level)</option>
                </select>
              </div>
            </div>

            <button
              onClick={handleStartTest}
              style={{ width: '100%', padding: '0.85rem', borderRadius: '0.75rem', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: 'white', fontWeight: '800', fontSize: '1rem', border: 'none', cursor: 'pointer' }}
            >
              🚀 Generate & Start {selectedCompany.name} Mock Test
            </button>
          </div>
        </>
      ) : (
        /* Test Active View */
        <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '1.25rem', padding: '2rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
            <div>
              <h3 style={{ color: 'white', fontWeight: '800', fontSize: '1.2rem' }}>{selectedCompany.logo} {selectedCompany.name} Mock Test</h3>
              <p style={{ color: '#94a3b8', fontSize: '0.85rem' }}>Role: {role} · Difficulty: {difficulty}</p>
            </div>
            <button onClick={() => setTestActive(false)} style={{ padding: '0.4rem 0.9rem', borderRadius: '0.5rem', background: 'rgba(255,255,255,0.1)', color: 'white', border: 'none', cursor: 'pointer', fontSize: '0.8rem' }}>Exit Test</button>
          </div>

          {!submitted ? (
            <div>
              <div style={{ color: '#fbbf24', fontWeight: '700', fontSize: '0.9rem', marginBottom: '0.5rem' }}>Question {currentQ + 1} of {activeQuestions.length}</div>
              <h4 style={{ color: 'white', fontWeight: '700', fontSize: '1.1rem', marginBottom: '1.25rem' }}>{activeQuestions[currentQ].question}</h4>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
                {activeQuestions[currentQ].options.map((opt, oIdx) => {
                  const isSelected = userAnswers[currentQ] === oIdx
                  return (
                    <button
                      key={oIdx} onClick={() => handleAnswerSelect(currentQ, oIdx)}
                      style={{
                        padding: '0.8rem 1.25rem', borderRadius: '0.75rem', textAlign: 'left', fontWeight: '600', fontSize: '0.9rem', cursor: 'pointer',
                        background: isSelected ? 'rgba(124,58,237,0.3)' : 'rgba(255,255,255,0.05)',
                        color: isSelected ? 'white' : '#cbd5e1',
                        border: `1px solid ${isSelected ? '#7c3aed' : 'rgba(255,255,255,0.1)'}`
                      }}
                    >
                      {String.fromCharCode(65 + oIdx)}. {opt}
                    </button>
                  )
                })}
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <button
                  disabled={currentQ === 0} onClick={() => setCurrentQ(prev => prev - 1)}
                  style={{ padding: '0.6rem 1.25rem', borderRadius: '0.6rem', background: 'rgba(255,255,255,0.06)', color: 'white', border: 'none', cursor: currentQ === 0 ? 'not-allowed' : 'pointer' }}
                >
                  ← Previous
                </button>
                {currentQ < activeQuestions.length - 1 ? (
                  <button
                    onClick={() => setCurrentQ(prev => prev + 1)}
                    style={{ padding: '0.6rem 1.25rem', borderRadius: '0.6rem', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: 'white', border: 'none', fontWeight: '700', cursor: 'pointer' }}
                  >
                    Next →
                  </button>
                ) : (
                  <button
                    onClick={() => { setSubmitted(true); toast.success('🎉 Test Submitted!'); }}
                    style={{ padding: '0.6rem 1.5rem', borderRadius: '0.6rem', background: 'linear-gradient(135deg, #10b981, #059669)', color: 'white', border: 'none', fontWeight: '800', cursor: 'pointer' }}
                  >
                    Submit Test 🎯
                  </button>
                )}
              </div>
            </div>
          ) : (
            /* Results View */
            <div>
              <div style={{ textAlign: 'center', padding: '1.5rem', background: 'rgba(255,255,255,0.03)', borderRadius: '1rem', marginBottom: '1.5rem' }}>
                <div style={{ fontSize: '3rem', marginBottom: '0.5rem' }}>{score === activeQuestions.length ? '🏆' : '📊'}</div>
                <h3 style={{ color: 'white', fontWeight: '900', fontSize: '1.5rem' }}>Your Score: {score} / {activeQuestions.length}</h3>
                <p style={{ color: '#4ade80', fontWeight: '700', fontSize: '1rem' }}>{Math.round((score / activeQuestions.length) * 100)}% Accuracy · +50 XP Earned! ⚡</p>
              </div>

              {/* Explanations */}
              <h4 style={{ color: 'white', fontWeight: '800', marginBottom: '1rem' }}>💡 Answers & Explanations</h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginBottom: '1.5rem' }}>
                {activeQuestions.map((q, idx) => {
                  const userAns = userAnswers[idx]
                  const isCorrect = userAns === q.answer
                  return (
                    <div key={idx} style={{ background: 'rgba(255,255,255,0.03)', border: `1px solid ${isCorrect ? 'rgba(74,222,128,0.3)' : 'rgba(239,68,68,0.3)'}`, borderRadius: '0.9rem', padding: '1rem' }}>
                      <div style={{ color: 'white', fontWeight: '700', fontSize: '0.95rem', marginBottom: '0.4rem' }}>{idx + 1}. {q.question}</div>
                      <div style={{ color: isCorrect ? '#4ade80' : '#ef4444', fontSize: '0.82rem', fontWeight: '700', marginBottom: '0.3rem' }}>
                        {isCorrect ? '✓ Correct Answer!' : `❌ Your Answer: ${userAns !== undefined ? q.options[userAns] : 'Not answered'}`}
                      </div>
                      <div style={{ color: '#4ade80', fontSize: '0.82rem', marginBottom: '0.4rem' }}>Correct: {q.options[q.answer]}</div>
                      <div style={{ color: '#94a3b8', fontSize: '0.8rem', background: 'rgba(0,0,0,0.3)', padding: '0.6rem', borderRadius: '0.5rem' }}>Explanation: {q.explanation}</div>
                    </div>
                  )
                })}
              </div>

              <button
                onClick={() => setTestActive(false)}
                style={{ width: '100%', padding: '0.8rem', borderRadius: '0.75rem', background: 'linear-gradient(135deg, #7c3aed, #2563eb)', color: 'white', fontWeight: '700', border: 'none', cursor: 'pointer' }}
              >
                Back to Company Selection
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
