import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import toast from 'react-hot-toast'

/**
 * Generates and downloads a formatted PDF for any academic study note
 * @param {Object} note - The full note object
 */
export async function downloadNotePDF(note) {
  if (!note) return
  const toastId = toast.loading('Generating study note PDF...')

  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 15
    const contentWidth = pageWidth - margin * 2
    let y = margin

    // ── Header Banner ──
    doc.setFillColor(30, 27, 75) // Dark Indigo
    doc.rect(0, 0, pageWidth, 28, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('CAMPUSPILOT AI — ACADEMIC STUDY NOTES', margin, 12)

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(196, 181, 253) // light purple
    doc.text(`Subject: ${note.subject || 'All Subjects'}  |  Branch: ${note.category || note.branch || 'Engineering'}  |  ${note.units || 'Unit Notes'}`, margin, 20)

    y = 36

    // ── Title & Meta ──
    doc.setTextColor(15, 23, 42)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    const splitTitle = doc.splitTextToSize(note.title, contentWidth)
    doc.text(splitTitle, margin, y)
    y += splitTitle.length * 6 + 2

    // Meta Badge bar
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(100, 116, 139)
    doc.text(`Level: ${note.level || 'Intermediate'}   |   Rating: ${note.rating || '4.8'}/5.0   |   Read Time: ${note.readTime || '15 min'}   |   Aligned: Anna Univ / VTU / JNTU`, margin, y)
    y += 5

    // Divider
    doc.setDrawColor(203, 213, 225)
    doc.line(margin, y, pageWidth - margin, y)
    y += 6

    // ── Body Content ──
    doc.setTextColor(30, 41, 59)
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'normal')

    const cleanContent = (note.content || '')
      .replace(/###/g, '')
      .replace(/##/g, '')
      .replace(/\*\*/g, '')
      .replace(/☐/g, '[ ]')

    const lines = doc.splitTextToSize(cleanContent, contentWidth)

    for (let i = 0; i < lines.length; i++) {
      if (y > pageHeight - 20) {
        // Footer on current page
        doc.setFontSize(8)
        doc.setTextColor(148, 163, 184)
        doc.text('Page ' + doc.internal.getNumberOfPages() + ' — Generated by CampusPilot AI (https://campus-pilot-ai-eta.vercel.app)', margin, pageHeight - 8)

        doc.addPage()
        y = margin + 5
      }

      const line = lines[i]
      if (line.startsWith('📌') || line.startsWith('🔢') || line.startsWith('📋') || line.startsWith('💡') || line.startsWith('🎯') || line.startsWith('Overview') || line.startsWith('Introduction')) {
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(79, 70, 229)
        y += 2
      } else {
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(30, 41, 59)
      }

      doc.text(line, margin, y)
      y += 4.8
    }

    // ── Exam Questions Section ──
    if (note.examQuestions && note.examQuestions.length > 0) {
      if (y > pageHeight - 40) {
        doc.addPage()
        y = margin + 5
      }

      y += 4
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(180, 83, 9)
      doc.text('📋 University Important Exam Questions', margin, y)
      y += 6

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(51, 65, 85)

      note.examQuestions.forEach((q, idx) => {
        if (y > pageHeight - 15) {
          doc.addPage()
          y = margin + 5
        }
        const qLine = `${idx + 1}. ${q.q}  [${q.mark}]`
        const splitQ = doc.splitTextToSize(qLine, contentWidth)
        doc.text(splitQ, margin, y)
        y += splitQ.length * 4.5 + 1
      })
    }

    // Final Footer
    const totalPages = doc.internal.getNumberOfPages()
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p)
      doc.setFontSize(8)
      doc.setTextColor(148, 163, 184)
      doc.text(`Page ${p} of ${totalPages} — CampusPilot AI Academic Hub`, margin, pageHeight - 8)
    }

    const filename = `${(note.title || 'Study_Note').replace(/[^a-zA-Z0-9_-]/g, '_')}_CampusPilot.pdf`
    doc.save(filename)
    toast.success('📥 Note PDF downloaded successfully!', { id: toastId })
  } catch (err) {
    console.error('PDF Generation Error:', err)
    toast.error('Failed to generate PDF. Please try again.', { id: toastId })
  }
}

/**
 * Generates and downloads a clean A4 PDF of the resume preview container
 * @param {HTMLElement|string} element - The DOM element or ID of the resume preview
 * @param {string} studentName - The student name for file naming
 */
export async function downloadResumePDF(elementOrId, studentName = 'Resume') {
  const toastId = toast.loading('Exporting high-resolution ATS Resume PDF...')

  try {
    const el = typeof elementOrId === 'string' ? document.getElementById(elementOrId) : elementOrId
    if (!el) {
      throw new Error('Resume element not found')
    }

    const canvas = await html2canvas(el, {
      scale: 2.5, // High resolution
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff'
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = pdf.internal.pageSize.getHeight()

    const imgWidth = canvas.width
    const imgHeight = canvas.height
    const ratio = Math.min(pdfWidth / (imgWidth / 2.5 * 0.264583), pdfHeight / (imgHeight / 2.5 * 0.264583))

    const renderWidth = (imgWidth / 2.5 * 0.264583) * ratio
    const renderHeight = (imgHeight / 2.5 * 0.264583) * ratio
    const posX = (pdfWidth - renderWidth) / 2
    const posY = 5

    pdf.addImage(imgData, 'PNG', posX, posY, renderWidth, renderHeight)

    const cleanName = (studentName || 'Student').replace(/[^a-zA-Z0-9_-]/g, '_')
    pdf.save(`${cleanName}_ATS_Resume_CampusPilot.pdf`)

    toast.success('📥 ATS Resume PDF exported successfully!', { id: toastId })
  } catch (err) {
    console.error('Resume PDF Export Error:', err)
    toast.error('Failed to export Resume PDF. Please try again.', { id: toastId })
  }
}
